  merge_multiline:
    type: lua
    inputs:
      - app_log
    version: '2'
    # search_dirs:
    #   - /etc/vector/lua
    source: |
    hooks:
      process: |
      shutdown: |
    timers:
      - handler: timer_handler
        interval_seconds: 5