humio_sink:
  type: humio_logs
  inputs: ["log_parser"]
  compression: none
  endpoint: https://schibsted.ingest.logscale.eu-1.crowdstrike.com
  event_type: json
  host_key: .host
  index: "io_schibsted_icc_mule_pre"
  timestamp_key: .@timestamp
  token: "${HUMIO_INGEST_TOKEN}"
  encoding:
    codec: "json"